<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <PackageId>Jaber.Mediator.Abstractions</PackageId>
        <Version>0.0.1</Version>
        <License>MIT</License>
        <Authors>Rafael Jáber</Authors>
        <Company>Jáber</Company>
        <PackageDescription>Abstractions for Mediator pattern implementation</PackageDescription>
        <Description>Abstractions for Mediator pattern implementation</Description>
        <RepositoryUrl>https://github.com/rafaeljaber/Jaber.Mediator.Abstractions</RepositoryUrl>
        <PackageProjectUrl>https://github.com/rafaeljaber/Jaber.Mediator.Abstractions</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>Mediator;Design Pattern;Dommain;DDD;</PackageTags>
        <Title>Mediator.Abstractions</Title>
        <Summary>Abstractions for Mediator pattern implementation</Summary>
        <RootNamespace>Mediator.Abstractions</RootNamespace>
    </PropertyGroup>
</Project>
